APP_VERSION = "0.2.0"

SCAN_STEPS = 10
STEP_DELAY = 1.0
CAPTURE_DELAY = 0.5

CAMERA_INDEX = 0

OUTPUT_FOLDER = "outputs/captures"

POINT_CLOUD_FOLDER = "outputs/point_clouds"
POINT_CLOUD_FILE = "scan_result.ply"

LASER_THRESHOLD = 180

MAX_LOG_LINES = 100

SIMULATION_MODE_DEFAULT = True

SCANS_FOLDER = "outputs/scans"